### ISSUE TITLE
Add a way to get the raw variant of search results

### ISSUE THREAD

**Issue by chrisseto** [CenterForOpenScience/ember-share#28]
![screen shot 2016-07-27 at 14 42 00](https://cloud.githubusercontent.com/assets/5532905/17187704/59f5ac74-5408-11e6-83e0-f506c0dd95a5.png)

pinging @leb2dg @karleywalker

**Comment by leb2dg** [comment]
Waiting on new endpoint so this is possible 🔚  👉

**Comment by aaxelb** [comment]
Depends on CenterForOpenScience/SHARE#364
